#!/bin/bash

cd ${OPENSHIFT_RAILO4_DIR}/versions/9.1.3/

CMD="java -Xms384m -Xmx412m -jar start.jar -Djetty.host=$OPENSHIFT_RAILO4_APP_HOST -Djetty.port=$OPENSHIFT_RAILO4_APP_PORT"

nohup $CMD > $OPENSHIFT_RAILO4_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid && echo "Jetty9 started successfully\n"


